### ISSUE TITLE
404 on AJAX Request  - (&cHash empty)

### ISSUE THREAD

**Issue by mittererr** [helhum/typoscript_rendering#10]
In TYPO3 7.5 I get a 404 when sending an AJAX Request. The Response is "Reason: Request parameters could not be validated (&cHash empty)". I have read of some possible modifications in UriBuilder.php which will prevent the issue. It works, I have testet it, but I don't want to make changes in the core. Is there another fix for this problem?

Thank you so much.

**Comment by helhum** [comment]
Still unfixed in the core :-/ see #8

**Comment by mittererr** [comment]
OK - thank you. Is there a file which works for 7.5 for download? I have changed the file on my own but I'm not really sure if I have done everything right.

**Comment by helhum** [comment]
No, but we merged the revert recently. I recommend that you update the TYPO3 sources to master. There will be no breaking changes any more until release of 7LTS

**Comment by helhum** [comment]
Fixed in 7LTS
