### ISSUE TITLE
add the composer install instruction to README?

### ISSUE THREAD

**Issue by maddy2101** [helhum/typoscript_rendering#11]
Hi,

I would be thankful for you to integrate this link into the README in order to make it easier on foolish people like me to install the extension via composer:
https://composer.typo3.org/satis.html#!/typoscript-rendering

If you want me to, I create a pull request, for now I just ask.

**Comment by helhum** [comment]
sure, go ahead.

Any further documentation is also welcome :)

**Comment by maddy2101** [comment]
done, thank you.
