### ISSUE TITLE
Possibility to distinguish AJAX call in extbase controller

### ISSUE THREAD

**Issue by cumuru** [helhum/typoscript_rendering#15]
Is there any way to distinguish an AJAX call to my extbase controller?
What I want to do is change fluid layout or redirect/forward depending on whether my controller was called via AJAX or "normally".
The only way I found is very low-level, looking for a GET variable:
```    
    /**
     * Checks if it‘s an AJAX call
     */
    protected function checkAjax()
    {
        $typoscriptRendering = GeneralUtility::_GET('tx_typoscriptrendering');
        $this->isAjax = isset($typoscriptRendering);
    }
```
Is there another way (e.g. in controller context or TSFE) to achieve this? This would facilitate development of hybrid applications…

**Comment by cumuru** [comment]
My comment wasn‘t precise: Of course, a way to check this would not facilitate development. The GET var check is neither expensive nor cumbersome.
Still, I do consider GET vars as implementation detail and as such subject to change. An API way would just feel more future proof.

**Comment by helhum** [comment]
I don't really see the use case to determine in the controller whether the call is done via Ajax or not.

Besides that, it is imho not in the domain of typoscript_rendering to provide such an API, but in the domain of the implementing controller if it really needs this.

A request argument can be used for this, which is added during link generation and be evaluated in the controller or the `HTTP_X_REQUESTED_WITH` header can be used to check the value `XMLHttpRequest`, as this header is sent by many Ajax client side implementations.

**Comment by cumuru** [comment]
My point was that the decision which rendering to use (typoscript_rendering‘s or pageGenScript) taken in `RenderingDispatcher::checkDataSubmission()` should be queryable afterwards IMHO. 
I‘d compare this to e.g. type parameter in 'normal' TYPO3 rendering. Of course you can query type GET var at any time but the actual decision to render page type x is written to TSFE->type from where it can be queried later.
I can live with situation as is, though, thanks for immersing :-)
