### ISSUE TITLE
The URI ViewHelper always builds paths relative to the root path

### ISSUE THREAD

**Issue by oliverklee** [helhum/typoscript_rendering#17]
I'm using the URI ViewHelper on a (RealURL-build) page http://www.example.com/community/ .

The URI ViewHelper now builds this URL:
community/?tx_typoscriptrendering%5Bcontext%5D=%7B%22record%22%3A%22tt_content_5472%22%2C%22path%22%3A%22tt_content.list.20.ppwsicommunity_communitymaincontent%22%7D&tx_ppwsicommunity_communitymaincontent%5Baction%5D=test&tx_ppwsicommunity_communitymaincontent%5Bcontroller%5D=Thread&cHash=45c1010b70afe90005acca584d9dc373

So either the "community/" needs to be removed (so that the path is truely relative), or the path must be absolute ( starting with "/community/...").

**Comment by helhum** [comment]
The viewHelper just uses the standard URI Builder. So you either need to set up a `config.absRefPrefix` or a `config.baseURL` in your global TYPO3 configuration. 

I would recommend `config.absRefPrefix` 

Is it really set?

**Comment by oliverklee** [comment]
Oh, we're actually using config.baseURL in that particular project, and the link works fine. So this was a false alarm.
