### ISSUE TITLE
Rendering is empty when PLUGIN_TYPE_CONTENT_ELEMENT is used

### ISSUE THREAD

**Issue by oliverklee** [helhum/typoscript_rendering#19]
This issue is a spin-off from PR #18.

When registering a plugin using \TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin with $pluginType = \TYPO3\CMS\Extbase\Utility\ExtensionUtility::PLUGIN_TYPE_CONTENT_ELEMENT (instead of the default type PLUGIN_TYPE_PLUGIN), the output is completely empty. (The corresponding action also never gets called.)

We most probably will be able to test this using the ajax_example extension (although I haven't checked yet).

From my debugging, I found out that PLUGIN_TYPE_PLUGIN creates a TS setup structure like tt_content.list.20.pluginname = USER while PLUGIN_TYPE_CONTENT_ELEMENT does not create it, but the typoscript_rendering extension relies on this when rendering the content element.

**Comment by helhum** [comment]
> From my debugging, I found out that PLUGIN_TYPE_PLUGIN creates a TS setup structure like tt_content.list.20.pluginname = USER while PLUGIN_TYPE_CONTENT_ELEMENT does not create it

From reading the code, it creates a structure with `tt_content.list.20.pluginname = COA`
If it wouldn't the plugin wouldn't show anything in frontend rendering.

Can you please verify if the content element works at all?

And can you please paste the generated Ajax URI here?

**Comment by oliverklee** [comment]
For both plugin types, the FE content elements works and displays its content. The plugin needs to be set in the content element in different ways, though:

PLUGIN_TYPE_CONTENT_ELEMENT:
* General > Content Element > Type: Forms > (the name of the plugin)
* Generated AJAX URL in my case:
    community/?tx_typoscriptrendering%5Bcontext%5D=%7B%22record%22%3A%22tt_content_5472%22%2C%22path%22%3A%22tt_content.list.20.ppwsicommunity_communitymaincontent%22%7D&tx_ppwsicommunity_communitymaincontent%5Baction%5D=create&tx_ppwsicommunity_communitymaincontent%5Bcontroller%5D=Thread&cHash=cedbdca3b0604d75cf6f904505b88434

PLUGIN_TYPE_PLUGIN:
* General > Content Element > Type: Insert Plugin
* Plugin > Selected Plugin: (the name of the plugin)
* Generated AJAX URL in my case:
    community/?tx_typoscriptrendering%5Bcontext%5D=%7B%22record%22%3A%22tt_content_5472%22%2C%22path%22%3A%22tt_content.list.20.ppwsicommunity_communitymaincontent%22%7D&tx_ppwsicommunity_communitymaincontent%5Baction%5D=create&tx_ppwsicommunity_communitymaincontent%5Bcontroller%5D=Thread&cHash=cedbdca3b0604d75cf6f904505b88434

**Comment by helhum** [comment]
Was a bit tougher to fix than expected. Should work now however.

Thanks for the report!

**Comment by oliverklee** [comment]
Thanks! ❤️
