### ISSUE TITLE
Error 500 in TYPO3 CMS 6.2 with RealURL when logged in to the BE

### ISSUE THREAD

**Issue by oliverklee** [helhum/typoscript_rendering#28]
Clicking the "Ajax Request with TypoScript Rendering" or "Hello World by TS-Rendering" link from the Ajax example extension creates an error 500 for the Ajax request. The same happens when using the "Greet! (Ajax)" button from the Ajax example.

The respective URLs are:

    http://typo362.local/ajax/?tx_typoscriptrendering%5Bcontext%5D=%7B%22record%22%3A%22tt_content_241%22%2C%22path%22%3A%22tt_content.list.20.ajaxexample_piexample%22%7D&tx_ajaxexample_piexample%5Baction%5D=hello&tx_ajaxexample_piexample%5Bcontroller%5D=Example&tx_ajaxexample_piexample%5Bformat%5D=json&cHash=7076269f00262e2d35e04e28711f0c1d
    http://typo362.local/ajax/?tx_typoscriptrendering%5Bcontext%5D=%7B%22renderer%22%3A%20%22hello%22%7D&cHash=76796c0753ea29fbae9826e23ba46469
    /ajax/?tx_typoscriptrendering%5Bcontext%5D=%7B%22record%22%3A%22tt_content_241%22%2C%22path%22%3A%22tt_content.list.20.ajaxexample_piexample%22%7D&tx_ajaxexample_piexample%5Baction%5D=greet&tx_ajaxexample_piexample%5Bcontroller%5D=Example&cHash=86e0382e47309e4a68742c2feef0221e

The problem occurs independent of whether the original page is loaded using the RealURL URL or the index.php?id=12341 URL.

This problem has occurred in two independent installations of mine using TYPO3 CMS 6.2 with RealURL 2.0.14 and the ajax_example with the 7.6 compatibility PR.

The problem does not occur under the same conditions on TYPO3 CMS 7.6. It also does not occur on 6.2 when RealURL is not installed. (I haven't tried what happens when RealURL is installed, but not enabled via TypoScript.)

For comparison, these are the URLs from the 7.6 installation:

    http://typo376.local/ajax/?tx_typoscriptrendering%5Bcontext%5D=%7B%22record%22%3A%22tt_content_14%22%2C%22path%22%3A%22tt_content.list.20.ajaxexample_piexample%22%7D&tx_ajaxexample_piexample%5Baction%5D=hello&tx_ajaxexample_piexample%5Bcontroller%5D=Example&tx_ajaxexample_piexample%5Bformat%5D=json&cHash=40b371ee52d0ce910859b251afb2c1ee
    http://typo376.local/ajax/?tx_typoscriptrendering%5Bcontext%5D=%7B%22renderer%22%3A%20%22hello%22%7D&cHash=096c0c1f810360e2b155f104479810e2
    /ajax/?tx_typoscriptrendering%5Bcontext%5D=%7B%22record%22%3A%22tt_content_14%22%2C%22path%22%3A%22tt_content.list.20.ajaxexample_piexample%22%7D&tx_ajaxexample_piexample%5Baction%5D=greet&tx_ajaxexample_piexample%5Bcontroller%5D=Example&cHash=5238c22d700e828ae0e61cfb2c88f0a7

**Comment by oliverklee** [comment]
This is the error message from the first Ajax request response:
https://dl.dropboxusercontent.com/u/27225645/error.html

**Comment by oliverklee** [comment]
For all four installations, I've been using the latest Git versions of typoscript_rendering, ajax_example (with the 7.6 compatibility PR) and the TYPO3 Core (6.2.x branch and 7.6.x branch).

**Comment by helhum** [comment]
I'm sorry. I cannot reproduce this. Also from the exception you get, there seems to be something really weird happening, as the `tx_typoscriptrendering[context]` which looks good in the URL, seems to have become malformed.

Can you debug `\Helhum\TyposcriptRendering\Mvc\RequestBuilder` and tell me the value of `$rawRequestArgument['context']` in the failing case?

**Comment by oliverklee** [comment]
Oh, this only happens when I'm logged in to the BE at the same time. I'll debug it in a second.

**Comment by oliverklee** [comment]
I'm debugging RequestBuilder::build.

With a BE session, ```$rawRequestArgument['context']``` is this:

    {\"record\":\"tt_content_241\",\"path\":\"tt_content.list.20.ajaxexample_piexample\"}

And without a BE session, it's this:

    {"record":"tt_content_241","path":"tt_content.list.20.ajaxexample_piexample"}

However, I've also noticed that without an active BE session, this method is only called if I have cleared the FE cache before that. On any subsequent identical Ajax requests, it's not called again.

**Comment by oliverklee** [comment]
On the machine that hosts the 6.2 installation (where the problem occurs) and the 7.6 installation (where the problem does not occur), both share the same PHP 5.6 installation with the same php.ini.

**Comment by helhum** [comment]
Thanks. Could reproduce it now. The cause is a bug in realurl: https://github.com/dmitryd/typo3-realurl/pull/198

**Comment by oliverklee** [comment]
Good to know. Thanks for tracking it down!
