### ISSUE TITLE
TYPO3 6.2.27 with [FE][cHashIncludePageId] = 1

### ISSUE THREAD

**Issue by infabo** [helhum/typoscript_rendering#30]
The yesterday released TYPO3 6.2.27 with the new configuration option

[FE][cHashIncludePageId] = 1

breaks all links generated with this plugin.

```
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1467983513: ID parameter needs to be passed for the cHash calculation! As a temporary not recommended workaround, you can set $GLOBALS['TYPO3_CONF_VARS']['FE']['cHashIncludePageId'] to false to avoid this error.
```

**Comment by oliverklee** [comment]
@helhum A customer of mine might want to sponsor the fixing of this issue. Would you be willing to fix this, and could you please email me an estimation?

**Comment by helhum** [comment]
> breaks all links generated with this plugin

typoscript_rendering does not call this API, which causes the Exception. So there must be another extension involved in link generation. Do you use realurl? If so, which version exactly?

> A customer of mine might want to sponsor the fixing of this issue

That is very generous, thanks. However this error is not related to typoscript_rendering.

`grep -r getRelevantParameters typo3conf/ext/` should list all usages, which might need a code change.

**Comment by infabo** [comment]
@helhum thanks for the clarification and the hint.
It was my strong guess, that it is typoscript_rendering causing the error, because a AJAX-call of typoscript-rendering-rendered-link (haha) from the browser was causing the 500 error.

I will have another look. Thank you.

**Comment by infabo** [comment]
As this has no direct relation to typo3script_rendering I will close this issue.
@helhum Thanks again for clearing this. I still don't have any clue what causes the error.

As already said, just calling the generated URL by ts-rendering and boooom. There are no calls to "getRelevantParameters" anywhere in my code. It may be be one of the view-helpers i am using inside the template/partial the controller-action is rendering - but there i am just using typo3-builtin-viewhelper (and no custom ones like vhs or alike).
This is strange and it makes me think, 6.2.27 was a shot from the hip and 6.2.28 is just a few days ahead....;)

**Comment by infabo** [comment]
I think it has nothing to do with simulatestatic in this case.
As already mentioned, the setting requires the id GET parameter to be present - otherwise the exception gets thrown.

Now the question is:
Is it the UriBuilder who is failing to build a correct link?
Or is it the ts-rendering ajax uri view-helper which needs to pass the page-id over to the uri-builder?

For reference:
https://github.com/TYPO3/TYPO3.CMS/commit/8aecd0c1f8654a6068b63c6ab76ea9a7f42a4205

**Comment by helhum** [comment]
> Seems really like an issue with simulatestatic in my case

You have simulatestatic installed? Please remove it and test again.

> is it simulatestatic/realurl to add the id?

If it works without simulatestatic, you'll have the answer :)

**Comment by helhum** [comment]
@infabo Please continue the discussion here:

https://forge.typo3.org/issues/77956

**Comment by infabo** [comment]
@helhum simulatestatic was causing it.

**Comment by helhum** [comment]
Thanks. Please also mention this fact here: https://forge.typo3.org/issues/77956
