### ISSUE TITLE
"Could not determine rendering location for plugin signature" in page template

### ISSUE THREAD

**Issue by Lumrenion** [helhum/typoscript_rendering#33]
Hi,
I am using the t:uri.ajaxAction viewhelper inside a partial of a page template implemented with the extension fluidpages. I am getting the exception "Could not determine rendering location for plugin signature". That is due to the fact that in method resolveRenderingPath, $this->renderingContext->getFrontendController()->tmpl->setup['tt_content.'] return NULL (see: https://github.com/helhum/typoscript_rendering/blob/master/Classes/Configuration/RecordRenderingConfigurationBuilder.php#L111)
I guess, the changes in a7dd7d8fa72e847135033fb5bdd5b59dd3992e71 cause that issue.
Of course that commit states that it might be a breaking change but it does not state how to correct this. Or am I missing something out?

For the time beeing I am switching back to Version 1.0.5, where everything works as expected (the controller action get's called correctly). But I would like to update to TYPO3 8.7 in the future, so thank you in advance for your advice!

- Philipp

**Comment by helhum** [comment]
> $this->renderingContext->getFrontendController()->tmpl->setup['tt_content.'] return NULL

In what context are you using the view helper? Question is: How can the TypoScript setup be null in your case?

**Comment by Lumrenion** [comment]
Hi and thanks for your reply,
Honestly, I have no clue why this problem occurred. It was quite persistent (clearing caches did not help). Now I tried to reproduce the error, installed Version 2.0.1 and it is gone.. clearing caches does not bring the problem back. If the problem comes occurres again, I will try to investigate it some more and come back here!

For the record, I still post my environment here:
I am using the extensions fluidpages and fluidcontent to build the entire frontend. Inside the page template (fluid) I render a partial. Inside that partial, the first ViewHelper used is the ajaxAction ViewHelper.

**Comment by helhum** [comment]
> If the problem comes occurres again, I will try to investigate it some more and come back here!

alright. Just comment here or open a new ticket
