### ISSUE TITLE
h:uri.action crashes after flux/fluidcontent update

### ISSUE THREAD

**Issue by TrueType** [helhum/typoscript_rendering#35]
Within render() the default contextRecord = 'current' makes it call getContentObject(), which returned NULL. Maybe we messed something up with our TYPO3. We "fixed" it by adding contextRecord: 'currentPage' in the helpers. But there should always be a contentObject, right?

**Comment by helhum** [comment]
Thanks for your report.

You need to give me more context on what your environment is, what you are exactly doing, what your expectations are and how the actual result is.

**Comment by helhum** [comment]
ah, ok, now I get it I think. But I have no Idea why the ConfigurationManager does not have a content object set. All TYPO3 core code sets it correctly. So I assume this to be a bug in flux/fluidcontent

**Comment by Lumrenion** [comment]
I just experienced the same issue.
In the controller, an Object of type `\FluidTYPO3\Flux\Configuration\ConfigurationManager` gets injected, which indeed has a ContentObject set. The named class extends class `\TYPO3\CMS\Extbase\Configuration\ConfigurationManager` and is an _Implementation_ of the ConfigurationManager_Interface_ (via $extbaseObjectContainer->registerImplementation).
In the viewhelper, the injected configurationmanager is of class `\TYPO3\CMS\Extbase\Configuration\ConfigurationManager`.  That means, we have to change the Annotation in the AjaxActionViewHelper from
>/**
>     * @var \TYPO3\CMS\Extbase\Configuration\ConfigurationManager
>     * @inject
> */

to
>/**
>     * @var \TYPO3\CMS\Extbase\Configuration\ConfigurationManagerInterface
>     * @inject
> */

As I recall correctly, the annotation should use the interface anyways, I am I right?
This Issue MIGHT be connected to #33

**Comment by helhum** [comment]
Good catch, thanks @Lumrenion 

Can you create a pull request that changes the annotation to use the interface?

**Comment by TrueType** [comment]
Can confirm the fix on my side. Thx.

**Comment by Lumrenion** [comment]
I will create a PR this evening
