### ISSUE TITLE
Realurl rewrites AJAX Uri

### ISSUE THREAD

**Issue by Haco** [helhum/typoscript_rendering#40]
When you rewrite your extension parameters with realurl (using your latest realurl fork) - by adding the below example configuration - the AJAX Uris will be invalid (action & controller arguments removed in ajax uri).

The below configuration can be used with your "ajax_example" extension for typoscript_rendering.
You can reproduce this when you click the "AJAX REQUEST WITH TYPOSCRIPT RENDERING (RECOMMENDED)" example.

 ```
            // Page UID where ajaxexample plugin is added
            '467' => [
                'ajaxexample' => [
                    [
                        'GETvar' => 'tx_ajaxexample_piexample[action]',
                        'valueMap' => [
                            // example extension actions
                            'list' => 'list',
                            'detail' => 'show',
                            // etc
                        ],
                        // If nomatch is bypass, ....[action]=hello is removed. => Ajax Request fails
                        // If nomatch is removed, ajax url is www.domain.com/page1/hello/?tx_typoscriptrendering... => Ajax Request fails
                        'noMatch' => 'bypass',
                    ],
                    [
                        // If you want to hide controller - But then the Parameter gets removed in the Ajax URI too. Request fails
                        'GETvar' => 'tx_ajaxexample_piexample[controller]',
                        'noMatch' => 'bypass',
                    ]
                ],
            ],
```

**Comment by helhum** [comment]
Thanks for the report.

Does everything work correctly without realurl?

**Comment by Haco** [comment]
Yes. And I'm also using it for other extensions - there are no rewritten URLs though.

**Comment by helhum** [comment]
> Yes

Well, then I don't know how I can change anything here to make it work *with* realurl, sorry. 😄 
It is either a bug in realurl then, or some misconfiguration (which I also can't see at first sight either).
