### ISSUE TITLE
Add composer.json

### ISSUE THREAD

**Issue by lorenzulrich** [helhum/typoscript_rendering#5]
It would be good to have a composer.json file

**Comment by helhum** [comment]
Sorry, I disagree here. I makes things more complicated. And even without it, it is easy to require the extension via composer with `typo3-ter/typoscript-rendering` as I released it to TER.

If I have special requirements to be specified in the composer.json, I will of course create one, until then I'd like to not have a second file with the exact same info in there.

**Comment by lorenzulrich** [comment]
You're right. Unless other extension authors, you do actually push the extension or its latest version to TER so it's no problem to require it from typo3-ter.

**Comment by lorenzulrich** [comment]
Maybe you should reconsider this. The current situation is that I cannot do a composer update when requiring typo3-ter/typoscript-rendering because I have a PHP 5.6 setup. I guess I cannot expect you to release a new version just because of the changed PHP dependencies, but I could easily use dev-master from GitHub if a composer.json was in place.
