### ISSUE TITLE
Typo3 v9 compatibility

### ISSUE THREAD

**Issue by ogrosko** [helhum/typoscript_rendering#52]
Will be there compatiblity with typo3 9?

**Comment by helhum** [comment]
I will try my best to make this possible, although a main „hook“ has been removed in that version.

**Comment by ogrosko** [comment]
Hmm, checking typo3 v9 changelog, I think the right approach would be [middleware](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.2/Feature-83725-SupportForPSR-15HTTPMiddlewares.html?highlight=middleware)

**Comment by helhum** [comment]
Yes, middleware looks promising. If you want to suggest a pull request, go ahead. would be helpful

**Comment by vendytjung** [comment]
@helhum pull request was added, but styleci failed. should i follow the styleci instructions to fix it?

**Comment by helhum** [comment]
Already released a 9.5 compatible version
