### ISSUE TITLE
additionalParams doesn't work in AjaxActionViewhelper

### ISSUE THREAD

**Issue by swilking** [helhum/typoscript_rendering#55]
The additionalParams parameter will be ignored.
t:uri.ajaxAction(additionalParams: '{tagUid:tag.uid}', action: 'filterTags')

I think "$additionalParams = $this->arguments['additionalParams'];" in start of the render-function fix this problem

**Comment by helhum** [comment]
Thanks. Will look into that.

**Comment by helhum** [comment]
Fixed with #56
