### ISSUE TITLE
"Real" json response

### ISSUE THREAD

**Issue by wtfred** [helhum/typoscript_rendering#57]
Hello,

I'm not sure if this is a typoscript_rendering issue, but i'll explain my problem:
My Extbase controller:
```
public function initializeUpdateViewsAjaxAction()
{
    $this->defaultViewObjectName = JsonView::class;
}

public function updateViewsAjaxAction(Fiche $fiche)
{
    ........
    ........

    $this->view->setVariablesToRender([
        'response',
    ]);
    $this->view->assign('response', ['status' => 'success']);
}
```
My template:
```
$.post('<f:uri.action action="updateViewsAjax" arguments="{fiche:fiche}" pageType="99" />')
   .done(function(data){console.log(data)});
$.post('<t:uri.action action="updateViewsAjax" pluginName="Videogallery" controller="Fiche" arguments="{fiche:fiche}" />')
   .done(function(data){console.log(data)});
```
Response for typeNum is "real" json : `{"status":"success"}`
Response for typoscript_rendering is "polluted" with html:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p>{"status":"success"}
</p></body></html>
```
This is on TYPO3 9.5
I tried with your extension ajax_example, on a TYPO3 8.7, and i got the same differences in the responses of `Ajax Request with Page Type (not recommended)` and `Ajax Request with TypoScript Rendering (recommended)`

Any idea where this comes from? Did i have some bad config somewhere or do you have the same behaviour?

Thanks!

**Comment by helhum** [comment]
@wtfred Thanks for the report and sorry, that I don't have an immediate idea.
The wrapping HTML tags also do not seem like they come from a standard TYPO3 installation and it also does not happen on my (TYPO3 8.7) [test instance](https://ajax.helhum.io/)

So I'd need some further information on your setup or, even better have you to try on a clean TYPO3 instance without any further setup involved.

Any more hints are welcome.

**Comment by wtfred** [comment]
@helhum i'm using bootstrap_package on 9.5 and 8.7, could it comes from it? I'll make more tests and let you know, thanks for answering me :)

**Comment by helhum** [comment]
@wtfred I still have no idea. But could you test 2.3.0 with TYPO3 9.5?

I added some code to deal with similar cases. Maybe this solves the issue for you as well.

**Comment by wtfred** [comment]
Hi Helmut, thanks for the following!
I'll let you know, but it may be in a bit of time, not sure when i could try...
