### ISSUE TITLE
Ajax Pagination in News doesnt work

### ISSUE THREAD

**Issue by droomdre** [helhum/typoscript_rendering#60]
I'm using this extension together with tx_news. I found out that the widget[@currentPage] is not taken into account when using the pagination. My link looks like this:
`<a data-container="45" data-link="/newsroom/aktuelles?tx_news_pi1%5Bcontroller%5D=ViewHelpers%5CWidget%5CPaginate&amp;tx_typoscriptrendering%5Bcontext%5D=%7B%22record%22%3A%22tt_content_45%22%2C%22path%22%3A%22tt_content.list.20.news_pi1%22%7D&amp;cHash=8dab4ebfdf6a3f3322334c6e" href="/newsroom/aktuelles?tx_news_pi1%5B%40widget_0%5D%5BcurrentPage%5D=2&amp;cHash=ed023c1a313f9e3d1d0f6e6e6a68fa44">2</a>`

Adding the following line at line 76 in the render() Function of AjaxActionViewHelper.php solves the problem:
`$additionalParams = $this->arguments['additionalParams'];`

**Comment by helhum** [comment]
@droomdre Thanks! Will take care of the fix as soon as I have time to.

**Comment by develth** [comment]
The line mentioned from @droomdre fixed the issue. A update would be nice.

**Comment by helhum** [comment]
What version are you using? Should be fixed in latest version. (see #56)

**Comment by develth** [comment]
Using 2.2.0 (from TER)

**Comment by NochEinKamel** [comment]
Composer already installed the fixed version 2.22. And I was going mad because it was "working on local machine" with a composer install but not the server without composer. 

Any chance to push the version to TER?

**Comment by helhum** [comment]
fixed and released (also in TER)
