### ISSUE TITLE
Additional query params

### ISSUE THREAD

**Issue by Mainbird** [helhum/typoscript_rendering#61]
Hi,

is it possible to add additional query params to ajax action view helper? I have tried something like that:

`{tr:uri.ajaxAction(action:'list',format:'html',controller:'Store',pluginName:'P1',additionalParams:'{no_cache:1,type:2}') -> f:format.htmlentities()}`

but the resulting URL will always lose this params. Did I miss something here?

**Comment by helhum** [comment]
Which version are you using? should be fixed in 2.1.0

**Comment by Mainbird** [comment]
I am using version 2.2.0.

**Comment by helhum** [comment]
Ah, sorry. This was fixed in 2.2.1. So please update.

**Comment by Mainbird** [comment]
Ok, thanks. It's working now.
