### ISSUE TITLE
Is pageNotFoundOnCHashError requirement really .. required?

### ISSUE THREAD

**Issue by X-Tender** [helhum/typoscript_rendering#65]
In my current project I have to disabled the `pageNotFoundOnCHashError` option, but your plugin requires it. I tried to comment it out in the source but realised that it doesn't work without the option. However, is there a way to make it run without the `pageNotFoundOnCHashError` option enabled?

**Comment by X-Tender** [comment]
Well I just noticed that when I add `&cachebuster=Math.random()*9000` to the ajax url that it works without the option. So could I break anything when I do it this way?

**Comment by helhum** [comment]
> However, is there a way to make it run without the pageNotFoundOnCHashError option enabled?

Short answer is: no

Long answer:

Currently cHash is used for caching *and* verification whether the arguments (especially the ts path and data set) are not tampered with. Without such verification an attacker could render arbitrary TS paths with arbitrary data sets, which eventually would lead to information disclosure.

While I thought about extracting the security check from cHash and adding a different verification argument to the URI, doing so will negatively affect the out of the box caching behaviour.

> Well I just noticed that when I add &cachebuster=Math.random()*9000 to the ajax url that it works without the option

This can only work, when you add the `cachebuster` argument to cHash excluded parameters, which I assume you did in your installation.

Conclusion is, that you **must not** change `pageNotFoundOnCHashError` to work with the extension, but *can* add arguments to `excludedParameters` for arguments you want to be able to add dynamically with JavaScript.

Does this answer your question?

**Comment by X-Tender** [comment]
I understand everything, except this part:
>Conclusion is, that you must not change pageNotFoundOnCHashError to work with the extension, but can add arguments to excludedParameters for arguments you want to be able to add dynamically with JavaScript.

When I disable `pageNotFoundOnCHashError` I get an exception thrown so I **have to** enable it (change for me) to make it work :)

I didn't added my cachebuster paraemter to the `excludedParameters` and it worked (with removed the check for `pageNotFoundOnCHashError`)

Just to be sure that we're talking about the same, thats the line:
```php
if (empty($GLOBALS['TYPO3_CONF_VARS']['FE']['pageNotFoundOnCHashError'])) {
  throw new Exception('$GLOBALS[\'TYPO3_CONF_VARS\'][\'FE\'][\'pageNotFoundOnCHashError\'] needs to be enabled when using out of bound typoscript rendering!', 1403808246);
}
```
It's inside the `TypoScriptRenderingMiddleware.php`

**Comment by helhum** [comment]
> (with removed the check for pageNotFoundOnCHashError)

Removing this check will lead to having a more or less severe security issue in your TYPO3 installation. It will allow attackers to provide arbitrary typoscript rendering paths with arbitrary records.

> I didn't added my `cachebuster` paraemter to the excludedParameters

What you should do instead is actually add this argument to `excludedParameters` and leave the code as is and keep `pageNotFoundOnCHashError` to be turned on (which is a good idea anyway).

**Comment by X-Tender** [comment]
Ok so I have to change the other codebase which depends on this option to be checked off.
Thanks you.

**Comment by AMartinNo1** [comment]
I just stumbled on this issue. On a project we (the team) decided to enable `pageNotFoundOnCHashError` for typoscript_rendering requests.

**Comment by X-Tender** [comment]
> I just stumbled on this issue. On a project we (the team) decided to enable `pageNotFoundOnCHashError` for typoscript_rendering requests.

How did you enabled it only for the typoscript_requests? @AMartinNo1

**Comment by AMartinNo1** [comment]
I have placed following code into `ext_localconf.php`.
```
if (isset($_GET['tx_typoscriptrendering'])) {
    $GLOBALS['TYPO3_CONF_VARS']['FE']['pageNotFoundOnCHashError'] = 1;
}
```

**Comment by helhum** [comment]
@X-Tender @AMartinNo1 I can only highly recommend to **not** disable pageNotFoundOnCHashError in general, but fix the code that does not cope with it.

Having it disabled leads to less performant and less secure websites.

**Comment by AMartinNo1** [comment]
@helhum I agree with you. Ideally the code would be fixed. I will push this, perhaps we can do that along with the next LTS upgrade
