### ISSUE TITLE
How to change the URL without reloading a page?

### ISSUE THREAD

**Issue by typo3ua** [helhum/typoscript_rendering#67]
I use your extension for Ajax-based pagination in the `ext: news` [form documentation](https://docs.typo3.org/p/georgringer/news/master/en-us/AdministratorManual/Templates/AjaxBasedPagination/Index.html). Everything works great but I have one but... 

After change page in the Ajax-based pagination I need to change URL-address, for example:

```
typo3.local/list/page/1/
typo3.local/list/page/2/
...
```
Currently, this does not happen ... I see just `typo3.local/list/`

How to change the URL without reloading a page via an extension `typoscript_rendering`?

**Comment by helhum** [comment]
Great question. This however has nothing to do with this extension, but correct use of [JavaScript API](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState)
