### ISSUE TITLE
AJAX-based pagination in the 'ext:news' works not respecting category and tag

### ISSUE THREAD

**Issue by typo3ua** [helhum/typoscript_rendering#69]
**I am using the AJAX based pagination like documented here:** 

[ext:news](https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/Templates/AjaxBasedPagination/Index.html)

Everything works fine. But if i have a filtered news list by categorie, the AJAX loader still loads all news.

**The href of the next Link is correct:**

`href="/index.php?id=7&amp;tx_news_pi1%5BoverwriteDemand%5D%5Bcategories%5D=9&amp;tx_news_pi1%5B%40widget_0%5D%5BcurrentPage%5D=2&amp;cHash=fe4d91b4ec30048fa42bdd310cc8675d"`

**But the data attribute ignores the categories parameter**

`data-link="/index.php?id=7&amp;tx_news_pi1%5B%40widget_0%5D%5BcurrentPage%5D=2&amp;tx_news_pi1%5Bcontroller%5D=ViewHelpers%5CWidget%5CPaginate&amp;tx_typoscriptrendering%5Bcontext%5D=%7B%22record%22%3A%22tt_content_36%22%2C%22path%`22%3A%22tt_content.list.20.news_pi1%22%7D&amp;cHash=3eca5db96c37c64eef0348c79f6a70b0"`

I am afraid, the AJAX Link also ignores the option excludeAlreadyDisplayedNews.

Source: [#594](https://github.com/georgringer/news/issues/594)

**System:**
TYPO3 9.5.11 (Not composer based)
News 7.3.1
typoscript_rendering: 2.2.2

**Comment by helhum** [comment]
> But if i have a filtered news list by categorie, the AJAX loader still loads all news

@typo3ua you need to set `addQueryString` to `true` for generating the links:

```diff
- <f:widget.link useCacheHash="1" arguments="{currentPage: pagination.previousPage}" data="{container:recordId,link:'{t:uri.ajaxAction(contextRecord:\'tt_content:{recordId}\', pluginName: \'pi1\',additionalParams:\'{n:widget.ajax.paginateAdditionalParams(page:pagination.previousPage)}\')}'}">
+ <f:widget.link useCacheHash="1" arguments="{currentPage: pagination.previousPage}" data="{container:recordId,link:'{t:uri.ajaxAction(contextRecord:\'tt_content:{recordId}\', pluginName: \'pi1\',addQueryString: true,additionalParams:\'{n:widget.ajax.paginateAdditionalParams(page:pagination.previousPage)}\')}'}">
```

> I am afraid, the AJAX Link also ignores the option excludeAlreadyDisplayedNews

That's unfixable unfortunately in the way this feature is implemented.
If you rely on this feature, no Ajax solution will get you there.

**Comment by helhum** [comment]
> no Ajax solution will get you there

except for one, that fetches the complete TYPO3 page and you pull out the correct DOM container with javascript of course...

**Comment by typo3ua** [comment]
Thank for you support! 

Do I have to make an update?

**Comment by helhum** [comment]
sorry, not sure whether `true` really works with latest fluid versions. Maybe try `addQueryString: '1'`:

```diff
- <f:widget.link useCacheHash="1" arguments="{currentPage: pagination.previousPage}" data="{container:recordId,link:'{t:uri.ajaxAction(contextRecord:\'tt_content:{recordId}\', pluginName: \'pi1\',additionalParams:\'{n:widget.ajax.paginateAdditionalParams(page:pagination.previousPage)}\')}'}">
+ <f:widget.link useCacheHash="1" arguments="{currentPage: pagination.previousPage}" data="{container:recordId,link:'{t:uri.ajaxAction(contextRecord:\'tt_content:{recordId}\', pluginName: \'pi1\',addQueryString: \'1\',additionalParams:\'{n:widget.ajax.paginateAdditionalParams(page:pagination.previousPage)}\')}'}">
```

**Comment by typo3ua** [comment]
Yeah, man! It does work.. you are cool... but I see a little bug...

I can click from 1 to 2 to 3 to 4 and so on...

I can click from 4 to 3 to 2...

...but can not click from 2 to 1... If I stay on 2 and want to click 1, I get nothing... I just stay on 2 and can not go to 1
