### ISSUE TITLE
version 2.2.0 should actually be version 3.0.0

### ISSUE THREAD

**Issue by simonschaufi** [helhum/typoscript_rendering#72]
Version 2.1.0 still supports TYPO3 8 and version 2.2.0 supports **only** version 9. In my opinion this should be a new major release as I can't update the package any more if I'm still using TYPO3 8. I explicitly need to require 2.1.0 instead of `^2.1`

**Comment by oliverklee** [comment]
@simonschaufi If I understand semantic versioning and Composer correctly, you will not be able to unstall version 2.2 if you require `^2.0` or `^2.1` in a TYPO3-8-only installation. So technically, this should not be a problem (even if it would be more semantic-versioning-like to tag that version as 3.0).

**Comment by simonschaufi** [comment]
@oliverklee if I explicitly require ^2.1 it works, right but `composer update` will always to try install `2.2` and `2.3` and so on.

**Comment by oliverklee** [comment]
@simonschaufi If I understand it correctly, it would not install version 2.2.0 if you also require `typo3/cms-core` in some 8.7 version. Or am I missing something here?

**Comment by simonschaufi** [comment]
`composer require helhum/typoscript-rendering:^2.1` worked for me.
