### ISSUE TITLE
TYPO3 Security Update 10.4.14 breaks typoscript_rendering partially

### ISSUE THREAD

**Issue by dsone** [helhum/typoscript_rendering#79]
When updating TYPO3 to https://get.typo3.org/release-notes/10.4.14 (or newer) this extension doesn't work properly anymore.

### The scenario
In TYPO3 version below 10.4.14 you set up the form according to https://www.comuno.net/blog/detail/formular-mit-typoscript-rendering-per-ajax-verschicken/.
No custom action, everything default. The form you use has a confirmation message and a mail-to-recipient finisher.

You submit the form via AJAX and get the confirmation message back in the form of this response
```
<div id="Contact-Formular-20">
     Thank you for getting into contact! We'll get back to you as soon as possible.
</div>
```
Everything fine and dandy so far.

### After Update to 10.4.14
You send the form via AJAX, the response is the entire page the form is on.
The mail finisher is executed but the confirmation message finisher is not send back.

This issue can be traced back to the "security" update of TYPO3 where several form related changes were made. 
Among them the refactoring of an entire class.
No clue how to mitigate this issue, though.

**Comment by helhum** [comment]
Thanks. I suggest you report this to TYPO3 bugtracker as well. Can you provide a test extension to for easier reproduction of this issue?

**Comment by dsone** [comment]
I've created a minimal extension for this: https://github.com/dsone/typo3_test_ext
The extension itself is called `test`, though, so rename the folder after cloning from `typo3_test_ext` to simply `test`.
Renaming an existing extension is a pain... 🙄 

I used the form in `Resources/Private/Templates/Form/Form.html` for testing. It's basically the same I used on another separate project where the above mentioned behaviour is reproducible.
However, with this extension in a "bare" TYPO3 v10.4.14-16 I wasn't able to trigger the Mail-Finisher, while on two other projects, one currently in production, I still can.
There's no setup changing anything on the form handling other than that necessary for typoscript_rendering in either of those projects. Other than that the behaviour is the same as described.

When I install the test extension and use the provided test form in a fresh TYPO3 10.4.14 or newer I get the tt_content form element HTML as an AJAX response. No finisher executed, ie no mail, no confirmation message.
When I downgrade to 10.4.13 it works flawlessly, I get a "Success" response, which is the configured confirmation message finisher and the mail is send.

The composer.json I used for the TYPO3 installation (renamed to txt, so Github doesn't complain):
[composer.txt](https://github.com/helhum/typoscript_rendering/files/6469251/composer.txt)

**Comment by helhum** [comment]
> I've created a minimal extension for this: dsone/typo3_test_ext

Managed to get this working in a test installation.

> You submit the form via AJAX and get the confirmation message back in the form of this response

I cannot reproduce that. Only the HTML of the form plugin itself is returned when using the TypoScript rendering URI, not the full page HTML. So typoscript_rendering is working as expected and I can't really help for other issues not related to this extension. Maybe ask for help on Slack or Stackoverflow to get community support.

> When I install the test extension and use the provided test form in a fresh TYPO3 10.4.14 or newer I get the tt_content form element HTML as an AJAX response. No finisher executed, ie no mail, no confirmation message.

Well, then this hasn't anything to do with typoscript_rendering, has it? One difference that I see between the ajax URL you are creating and the original form action URL is that your ajax URI misses the action argument.

I changed it to:

```
additionalAttributes="{data-ajaxuri: '{t:uri.ajaxAction(action: \'perform\', additionalParams:\'{no_cache:1}\',contextRecord: \'tt_content:{objData.uid}\', pageUid: \'{pageData.uid}\')}'}"
```

Maybe this helps already, if not, please reach out in other community support channels as mentioned above, as I can't help any further. Thanks

**Comment by dsone** [comment]
> I cannot reproduce that.
> Only the HTML of the form plugin itself is returned when using the TypoScript rendering URI, not the full page HTML. So typoscript_rendering is working as expected
This is a bit ambigous wording. With the test extension and the composer.json:
* In TYPO3v10.4.13 and below: I get the confirmation message as a response back. That is `<div id="testform-3">Success</div>`
* In TYPO3v.10.4.14 and above: I get the form's HTML as a response, just as the form is rendered on the page when I load the page.
I'd be surprised if that is not reproducible for you when I can reproduce this behaviour in three separate environments.

However, I guess the culprit might actually be the missing action in 10.4.14 and above as with it it works.
I appreciate you taking your time.
