### ISSUE TITLE
cHash issues after TYPO3 upgrade from 7.0 to 7.2

### ISSUE THREAD

**Issue by jonaseberledmind** [helhum/typoscript_rendering#8]
After upgrading to Typo3 v7.2.0 from 7.0 we realized that the hook

['SC_OPTIONS']['tslib/class.tslib_fe.php']['checkDataSubmission']

might be called too late for typoscript_rendering-URLs. The request gets redirected to the pageNotFound_handling before the hook gets called. On other pages (with correct cHash) it gets called.
Do you have an idea which other hook we could use to intercept the typoscript_rendering-requests?

**Comment by helhum** [comment]
I don't understand that. A wrong cHash should not (and afaik does not) call the hook, not even in TYPO3 6.2 and that is also not intended, because in that case something is wrong and parameters may have been spoofed.

So what exactly is your issue?

**Comment by jonaseberledmind** [comment]
The problem is that typoscript_rendering does not work in Typo3 7.2. The hook it uses does not get called and the request is redirected to the 404-page.

**Comment by helhum** [comment]
> the request is redirected to the 404-page

This is indeed the case when the cHash is wrong. So can you please find out why this is the case? How do you generate the links? Do you use realurl?

**Comment by helhum** [comment]
The extension works perfectly for me in current master btw. …

**Comment by jonaseberledmind** [comment]
Ok, that's good to know.
realurl is installed, but not yet active
The URIs are generated via the uri.ajaxAction-viewhelper:
<pre>{h:uri.ajaxAction(action: 'new', arguments : {format:'json', objektnrextern : '20004-7310'})}</pre>
Out of the same extension, plugin and controller (that's why we leave that out). 
The links look like:
http://domain/index.php?id=28&tx_typoscriptrendering[context]={%22record%22%3A%22tt_content_113%22%2C%22path%22%3A%22tt_content.list.20.wib24merkzettel_merkzettelplugin%22}&tx_wib24merkzettel_merkzettelplugin[format]=json&tx_wib24merkzettel_merkzettelplugin[objektnrextern]=20004-7310&tx_wib24merkzettel_merkzettelplugin[action]=delete&tx_wib24merkzettel_merkzettelplugin[controller]=Merkzettel

So there is actually no cHash. I just checked typoscript_rendering in another project (Typo3 v7.2): there a cHash is attached.

Thank you for looking into that

**Comment by helhum** [comment]
> So there is actually no cHash. I just checked typoscript_rendering in another project (Typo3 v7.2): there a cHash is attached.

Yes. We changed that in Extbase that if a link is generated from an uncached action to another uncached action, the cHash is dropped by default.

Now we have an issue here, as typoscript_rendering *requires* a cHash and there is no possibility to force the URI builder to generate one :-/

We need to fix the core imho

**Comment by jonaseberledmind** [comment]
Thank you for that insight.
I guess we will just patch \TYPO3\CMS\Extbase\Mvc\Web\Routing\UriBuilder::disableCacheHashForNonCacheableAction() and wait for it to disappear or be configurable in an upcoming Typo3-version.

**Comment by helhum** [comment]
Identified as TYPO3 core issue

**Comment by mbrodala** [comment]
This is tracked upstream with [issue #67097](https://forge.typo3.org/issues/67097)

**Comment by jonaseberledmind** [comment]
Thank you both!

**Comment by helhum** [comment]
Fix is here: https://review.typo3.org/#/c/39657

**Comment by jonaseberledmind** [comment]
Works. Many thanks.
