### ISSUE TITLE
TYPO3 v11 compatibility

### ISSUE THREAD

**Issue by mhirdes** [helhum/typoscript_rendering#81]
Any plans to go ready for v11? Do you need help?

**Comment by RostyslavMatviyiv** [comment]
Would be awesome 👍

**Comment by helhum** [comment]
> Any plans to go ready for v11?

Sure. It will be ready when it's ready.
Did you test it out with typo3 11 already?
I'm not expecting big changes (if any changes at all) to be necessary. 

> Do you need help?

Of course, always. 
Helping yourself will help me and others: Testing and fixing it will make it work in your project(s). Creating a PR will enable others to use it and help out with further testing.

**Comment by helhum** [comment]
Released 2.4.0 now. I would be very grateful if everybody here could give it a test and provide feedback. Thanks!
